import { Info } from 'lucide-react';

/**
 * Professional AI-generated content disclaimer.
 * Displayed on result pages and feedback reports to inform users
 * that AI assessments may contain inaccuracies and should be
 * reviewed by a qualified instructor.
 */
export default function AIDisclaimer() {
  return (
    <div className="mt-4 p-3 bg-amber-50 dark:bg-amber-950/20 border border-amber-200 dark:border-amber-800/40 rounded-xl">
      <div className="flex gap-2.5">
        <Info className="w-4 h-4 text-amber-600 dark:text-amber-400 mt-0.5 shrink-0" />
        <p className="text-xs text-amber-800 dark:text-amber-300 leading-relaxed">
          This assessment was generated by artificial intelligence and may contain
          inaccuracies or inconsistencies. Scores and feedback should be reviewed
          by a qualified instructor before being used for grading or placement decisions.
        </p>
      </div>
    </div>
  );
}
